name: Destroy Workflow

on:
  workflow_dispatch

jobs:
  terraform_destroy:
    name: Destroy - Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: AWS Login
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Ajuste para a sua região da AWS

      - name: Check Commit Message for [destroy]
        id: check_commit
        run: echo ::set-output name=DESTROY::$(if echo "${{ github.event.workflow_run.payload.commits[0].message }}" | grep -q "\[destroy\]"; then echo "true"; else echo "false"; fi)

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Ajuste para a versão desejada do Terraform

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./

      - name: Terraform Destroy
        if: steps.check_commit.outputs.DESTROY == 'true'
        run: terraform destroy -var-file="prod.tfvars" -auto-approve
        working-directory: ./
